spring:
  jpa:
    hibernate:
      #ddl-auto: none
      #ddl-auto: update
    show-sql: true
  # MySQL
  datasource:
    url: jdbc:mysql://localhost:3306/eduapp
    username: root
  sql:
    init:
      #mode: always

jwt:
  secret: jwt_frase_secreta_xd
  jwtExpirationMs: 3600000
  jwtRefreshExpirationMs: 86400000

# Swagger ui
spring-doc:
  paths-to-match:
    - /api/**